Ft schedule a trip 25
BuildForSDG/FASTA pull request #66
Opened 2020-06-02 09:29 UTC by myquery

## Description
Implemented the endpoint to save schedule trip to db

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:

## How Has This Been Tested
All the endpoint has been tested by postman 

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [x ] I have added tests that prove my fix is effective and that this feature works
- [x ] New and existing unit tests pass locally with my changes

2020-06-02 17:08 UTC, danthecm requested changes
Nice one @myquery your PR has merge conflict kindly resolve them
Thanks

2020-06-02 19:48 UTC, yerimaisaac submitted a review, later dismissed

2020-06-04 19:02 UTC, phawazzzy commented
fixed this merged conflicts and the codacy errors....please someone should have it tested before merging 
@myquery 
@shammahk 
@danieletchie

2020-06-04 21:39 UTC, thevetdoctor approved these changes
Nice. You however forgot to import the ScheduleTrip Model in your route!
Fixed.
Got a response => {"response":"Your Trip Details are saved!"}

2020-06-05 06:49 UTC, danthecm approved these changes

2020-06-05 06:57 UTC, merged